# This is a basic workflow to help you get started with Actions

name: Issues comment

# Controls when the workflow will run
on:
  issues:
    types: [opened]



  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  comment-with-action:
    runs-on: ubutu-latest
    steps:
      - name: "dump github context"
        run: echo '${{ toJSON(github.event)}} | jq
        shell: bash
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.issue.number}}
          body: |
            This is a multi-line test comment
            - With GitHub **Markdown** :sparkles:
            - Created by [create-or-update-comment][1]

            [1]: https://github.com/peter-evans/create-or-update-comment
          reactions: '+1'
  
